// Decides what a command page is allowed to claim a command printed. Two kinds of thing
// are handled, and nothing else:
//
//   1. Artifacts of running under the harness, which nobody typing the command sees:
//      bash's line numbers, curl's progress meter, wget's redrawn bar, ssh's
//      pseudo-terminal warning. These are *stripped*, and the stripped text is what a page
//      is written with.
//   2. Values nothing can pin, coming from the clock or the machine. These are *masked*,
//      and only while comparing two runs — a mask must never reach a page.
//
// Every mask is anchored to the line shape that produces it. An unanchored one is more
// dangerous than it looks: a bare `\d{4}-\d{2}-\d{2}` also matches a date inside a
// fixture's contents, so the file a page claims to show could drift and still pass.
// Anything not listed here must match byte for byte; prefer making an example
// deterministic over adding a rule.
//
// Covered by test/normalise.test.ts. Add a case there alongside anything added here.

/** The tokens a mask can introduce. verify-examples rejects a page containing one: they
 *  belong to a comparison, and on a page they would read as literal placeholders and match
 *  any future output for ever. */
export const MASK_TOKENS: readonly string[] = ["<TIMESTAMP>", "<RATE>", "<VOLATILE>", "<ELAPSED>"];

/** Timestamps, each anchored to the column of the command that emits it.
 *
 *  `diff -u`/`-c` headers  ->  `--- old.conf\t2026-08-15 10:09:33.149381006 +0000`
 *  `tar -tvf`              ->  `-rw-r--r-- user/user  120 2026-08-15 18:21 site/a.txt`
 *  wget's report           ->  `--2026-08-15 21:37:59--  http://...`
 *                              `2026-08-15 21:37:59 (49.0 MB/s) - 'a.html' saved`
 *                              `2026-08-15 21:37:59 URL:http://... [120/120] -> ...`
 *                              `2026-08-15 21:37:59 ERROR 500: Internal Server Error.`
 *  wget's cookie jar       ->  `# Generated by Wget on 2026-08-15 21:38:08.`
 *
 *  Not masked: an `ls -l --time-style=long-iso` column, which shows an mtime the fixtures
 *  pin exactly, and any date in file content. A page is held to both. */
const timestamps = (s: string): string =>
  s
    // diff headers: three markers, a filename, a tab, then the mtime.
    .replace(/^([-+*]{3} \S+\t)\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(\.\d+)?( [+-]\d{4})?$/gm, "$1<TIMESTAMP>")
    .replace(/^([-+*]{3} \S+\t)(Mon|Tue|Wed|Thu|Fri|Sat|Sun) [A-Z][a-z]{2} +\d+ \d{2}:\d{2}:\d{2} \d{4}$/gm, "$1<TIMESTAMP>")
    // tar -tvf: mode, owner/group, size, then the mtime, then the member name.
    .replace(/^(\S{10} +\S+\/\S+ +\d+ )\d{4}-\d{2}-\d{2} \d{2}:\d{2}(?= )/gm, "$1<TIMESTAMP>")
    // wget: the line that opens a transfer, and the line that closes one.
    .replace(/^--\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}--(?=  )/gm, "--<TIMESTAMP>--")
    .replace(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(?= (\(|URL:|ERROR ))/gm, "<TIMESTAMP>")
    .replace(/^(# Generated by Wget on )\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(?=\.$)/gm, "$1<TIMESTAMP>");

/** Transfer rates and elapsed times: properties of the machine, not of the command.
 *
 *  `tar --totals`  ->  `Total bytes written: 30720 (30KiB, 305MiB/s)`
 *  wget's summary  ->  `<TIMESTAMP> (49.0 MB/s) - 'page.html' saved [120/120]`
 *  curl -m         ->  `curl: (28) Operation timed out after 2001 milliseconds ...`
 *  curl -w         ->  `time_total=0.230857s` */
const rates = (s: string): string =>
  s
    .replace(/^(Total bytes written: \d+ \([0-9.]+[KMG]?i?B, )\d+(\.\d+)?[KMG]iB\/s\)$/gm, "$1<RATE>)")
    .replace(/^(<TIMESTAMP> )\(\d+(\.\d+)? [KMGT]?B\/s\)(?= - )/gm, "$1(<RATE>)")
    .replace(/^(curl: \(28\) Operation timed out after )\d+(?= milliseconds)/gm, "$1<ELAPSED>")
    .replace(/^(time_total=)\d+(\.\d+)?s$/gm, "$1<ELAPSED>s");

/* Response headers are not masked: every example printing them talks to
 * scripts/fixtures/http-mock.py, which pins its own Date and Last-Modified so those lines
 * can be published and checked like any other. `<VOLATILE>` has no producer for that
 * reason, and stays in MASK_TOKENS so the guard still recognises it on an older page. */

/** wget redraws its progress bar with carriage returns and sizes it to the terminal, so no
 *  single frame is worth publishing. Matched one line at a time, never across lines.
 *
 *  wget brackets the bar with a blank line on each side; the one that follows goes with it,
 *  so a page shows
 *
 *      Saving to: 'page.html'
 *                                        <- one blank line: the bar was here
 *      2026-08-15 21:37:59 (49.0 MB/s) - 'page.html' saved [120/120]
 *
 *  rather than two consecutive blank lines around a hole. */
const wgetBars = (s: string): string => s.replace(/^[ \t]*\d+K[ .]+.*?\d+%.*\n?(?:[ \t]*\n)*/gm, "");

/** curl shows a progress meter whenever its output is not a terminal — here, always.
 *  Successive updates are separated by carriage returns, so the whole meter arrives as
 *  one physical line. Matching on "--:--:--" rather than the column layout keeps this
 *  working whatever suffixes the sizes and rates pick up (120, 163k, 1.2M). */
const curlMeter = (s: string): string =>
  s
    .replace(/^\s*% Total\s+% Received.*$\n?/gm, "")
    .replace(/^\s*Dload\s+Upload.*$\n?/gm, "")
    .replace(/^[^\n]*--:--:--[^\n]*$\n?/gm, "");

/** `bash -c` numbers its diagnostics; an interactive shell does not. ssh warns about the
 *  missing terminal for the same reason. */
const shellNoise = (s: string): string =>
  s
    .replace(/^bash: line \d+: /gm, "bash: ")
    .replace(/^Pseudo-terminal will not be allocated because stdin is not a terminal\.\n/gm, "");

/** Removes only the artifacts of running under the harness, leaving every real value
 *  intact. This is what gets written into a page: a reader typing the command sees
 *  exactly this, minus nothing they would actually have seen.
 *
 *  Whitespace handling is asymmetric on purpose: trailing spaces and surrounding blank
 *  lines go, but leading spaces on a content line stay. `wc` and `uniq -c` right-align
 *  their first column, and a plain `.trim()` would strip exactly the padding that
 *  `output: |2` exists to preserve. */
export function stripArtifacts(text: string): string {
  const trimmed = text
    // Per line, and never `\s`, which matches `\n` and would eat the blank line after any
    // line with a trailing space. `\r` is included because HTTP is a CRLF protocol:
    // `curl -i` ends every header line with one, and YAML would carry it into the page as
    // a byte no terminal shows and no reader can type.
    .replace(/[ \t\r]+$/gm, "")
    .replace(/^\n+/, "")
    .replace(/\n+$/, "");
  return wgetBars(curlMeter(shellNoise(trimmed)));
}

/** stripArtifacts, plus masking of values nothing can pin. Only ever used to compare a page
 *  against a fresh run: writing this to a page would leave
 *  Order matters: `rates` matches wget's summary line only after `timestamps` has replaced
 *  the stamp that opens it. */
export function normalise(text: string): string {
  return rates(timestamps(stripArtifacts(text)));
}

/** Reduces output to its structure, for an example declared `volatile:` — one whose output
 *  is real but contains a value from the clock, the machine or the network.
 *
 *  What varies is masked; everything else must still match, so a renamed field, a vanished
 *  line or an error where there was none all change the shape:
 *
 *    quantity   288K, 1.7M, 261ms, 2min   a number and its unit move together — a service
 *                                         up for 261ms today is up for 2min tomorrow, and
 *                                         masking only the digits would leave ms vs min
 *    weekday    Mon, Tue                  clock-derived, and not digits
 *    month      Jan, Feb                  the same
 *    identifier 59fc699d36de4013          an invocation or container id
 *    digits     87, 4699                  a pid, a limit, a count
 *    padding    two spaces vs five        a column shifts when its number changes width
 *
 *  Order matters: a quantity is matched before its digits are, and an identifier before the
 *  digits inside it are broken up. */
export function shapeOf(text: string): string {
  return stripArtifacts(text)
    .replace(/\b\d+(\.\d+)?\s?(ms|s|min|h|d|us|ns|B|K|M|G|T|KB|MB|GB|TB|KiB|MiB|GiB|TiB)\b/g, "Q")
    .replace(/\b(Mon|Tue|Wed|Thu|Fri|Sat|Sun)\b/g, "D")
    .replace(/\b(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\b/g, "M")
    .replace(/\b[0-9a-f]{8,}\b/gi, "x")
    .replace(/\d+/g, "0")
    .replace(/[ \t]+/g, " ");
}
