// Shared by scripts/verify-examples.mjs and scripts/adopt-real-output.mjs.
//
// Both have to agree exactly: verify compares the page against normalised output, and
// adopt writes stripped output into the page. When they drifted apart, adopt baked
// curl's progress meter into a page that verify would then reject — twice.
//
// Two kinds of thing are handled here, and nothing else:
//
//   1. Artifacts of how the harness runs a command, which a reader typing the same
//      command interactively would never see (bash's line numbers, curl's progress
//      meter, wget's redrawn progress bar, ssh's pseudo-terminal warning). These are
//      *stripped*, and the stripped text is what gets written onto a page.
//   2. Values that no fixture can pin because they come from the clock, the machine, or
//      the network. These are *masked*, and only when comparing — never on a page.
//
// Every mask is anchored to the line shape that produces it, naming the command in a
// comment. An unanchored mask is far more dangerous than it looks: `\d{4}-\d{2}-\d{2}`
// applied to a whole output also matches a date inside a fixture's *contents*, so the
// file the page claims to show could drift arbitrarily and still pass. Anchoring keeps
// the mask on the one column that genuinely cannot be pinned. Anything else must match
// byte for byte; prefer making the example deterministic over adding a rule here.
//
// Covered by test/normalise.test.ts. Add a case there for anything added here.

/** The tokens a mask can introduce. verify-examples.mjs rejects a page whose documented
 *  output contains one: they exist for the duration of a comparison and must never be
 *  written to a page, where they would read as literal placeholders to a reader. */
export const MASK_TOKENS = ["<TIMESTAMP>", "<RATE>", "<VOLATILE>", "<ELAPSED>"];

/** Timestamps, each anchored to the column of the command that emits it.
 *
 *  `diff -u`/`-c` headers  ->  `--- old.conf\t2026-08-15 10:09:33.149381006 +0000`
 *  `tar -tvf`              ->  `-rw-r--r-- user/user  120 2026-08-15 18:21 site/a.txt`
 *  wget's report           ->  `--2026-08-15 21:37:59--  http://...`
 *                              `2026-08-15 21:37:59 (49.0 MB/s) - 'a.html' saved`
 *                              `2026-08-15 21:37:59 URL:http://... [120/120] -> ...`
 *                              `2026-08-15 21:37:59 ERROR 500: Internal Server Error.`
 *  wget's cookie jar       ->  `# Generated by Wget on 2026-08-15 21:38:08.`
 *
 *  Deliberately *not* masked: an `ls -l --time-style=long-iso` column, which on these
 *  pages shows a server-set mtime the fixtures pin exactly, and any date appearing in
 *  file content. Both are things a page should be held to. */
const timestamps = (s) =>
  s
    // diff headers: three markers, a filename, a tab, then the mtime.
    .replace(/^([-+*]{3} \S+\t)\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(\.\d+)?( [+-]\d{4})?$/gm, "$1<TIMESTAMP>")
    .replace(/^([-+*]{3} \S+\t)(Mon|Tue|Wed|Thu|Fri|Sat|Sun) [A-Z][a-z]{2} +\d+ \d{2}:\d{2}:\d{2} \d{4}$/gm, "$1<TIMESTAMP>")
    // tar -tvf: mode, owner/group, size, then the mtime, then the member name.
    .replace(/^(\S{10} +\S+\/\S+ +\d+ )\d{4}-\d{2}-\d{2} \d{2}:\d{2}(?= )/gm, "$1<TIMESTAMP>")
    // wget: the line that opens a transfer, and the line that closes one.
    .replace(/^--\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}--(?=  )/gm, "--<TIMESTAMP>--")
    .replace(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(?= (\(|URL:|ERROR ))/gm, "<TIMESTAMP>")
    .replace(/^(# Generated by Wget on )\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(?=\.$)/gm, "$1<TIMESTAMP>");

/** Transfer rates and elapsed times: properties of the machine, not of the command.
 *
 *  `tar --totals`  ->  `Total bytes written: 30720 (30KiB, 305MiB/s)`
 *  wget's summary  ->  `<TIMESTAMP> (49.0 MB/s) - 'page.html' saved [120/120]`
 *  curl -m         ->  `curl: (28) Operation timed out after 2001 milliseconds ...`
 *  curl -w         ->  `time_total=0.230857s` */
const rates = (s) =>
  s
    .replace(/^(Total bytes written: \d+ \([0-9.]+[KMG]?i?B, )\d+(\.\d+)?[KMG]iB\/s\)$/gm, "$1<RATE>)")
    .replace(/^(<TIMESTAMP> )\(\d+(\.\d+)? [KMGT]?B\/s\)(?= - )/gm, "$1(<RATE>)")
    .replace(/^(curl: \(28\) Operation timed out after )\d+(?= milliseconds)/gm, "$1<ELAPSED>")
    .replace(/^(time_total=)\d+(\.\d+)?s$/gm, "$1<ELAPSED>s");

/* There is deliberately no HTTP-header mask any more. There was one — it replaced `date:`,
 * `age:`, `cf-ray:` and friends with `<VOLATILE>` — and it existed because the curl page
 * printed headers from a real host through Cloudflare. Every example that prints response
 * headers now talks to scripts/fixtures/http-mock.py, which pins its own Date and
 * Last-Modified precisely so those lines can be published and checked like any other. The
 * few examples that still reach the public internet don't print headers.
 *
 * `<VOLATILE>` stays in MASK_TOKENS despite having no producer: pages written while the
 * mask existed carry it, and the guard has to keep recognising it. */

/** wget redraws its progress bar with carriage returns and sizes it to the terminal, so
 *  no single frame is worth publishing: strip it outright. Confined to one line — an
 *  earlier version used `[\s\S]*?` to reach the percentage and could swallow every real
 *  line between a `64K` line and the next `%` anywhere below it.
 *
 *  wget brackets the bar with a blank line on each side. The one that follows goes with
 *  the bar, so what a page shows is
 *
 *      Saving to: 'page.html'
 *                                        <- one blank line: the bar was here
 *      2026-08-15 21:37:59 (49.0 MB/s) - 'page.html' saved [120/120]
 *
 *  rather than two consecutive blank lines around a hole. */
const wgetBars = (s) => s.replace(/^[ \t]*\d+K[ .]+.*?\d+%.*\n?(?:[ \t]*\n)*/gm, "");

/** curl shows a progress meter whenever its output is not a terminal — here, always.
 *  Successive updates are separated by carriage returns, so the whole meter arrives as
 *  one physical line. Matching on "--:--:--" rather than the column layout keeps this
 *  working whatever suffixes the sizes and rates pick up (120, 163k, 1.2M). */
const curlMeter = (s) =>
  s
    .replace(/^\s*% Total\s+% Received.*$\n?/gm, "")
    .replace(/^\s*Dload\s+Upload.*$\n?/gm, "")
    .replace(/^[^\n]*--:--:--[^\n]*$\n?/gm, "");

/** `bash -c` numbers its diagnostics; an interactive shell does not. ssh warns about the
 *  missing terminal for the same reason. */
const shellNoise = (s) =>
  s
    .replace(/^bash: line \d+: /gm, "bash: ")
    .replace(/^Pseudo-terminal will not be allocated because stdin is not a terminal\.\n/gm, "");

/** Removes only the artifacts of running under the harness, leaving every real value
 *  intact. This is what gets written into a page: a reader typing the command sees
 *  exactly this, minus nothing they would actually have seen.
 *
 *  Whitespace handling is deliberately asymmetric. Trailing spaces go (no page should
 *  carry invisible padding at the end of a line) and so do leading and trailing *blank*
 *  lines, but leading spaces on a content line never do: `wc` and `uniq -c` right-align
 *  their first column, and a plain `.trim()` here silently unpicked the first line's
 *  padding on every page it touched — the exact defect `output: |2` exists to prevent. */
export function stripArtifacts(text) {
  const trimmed = text
    // Per line, and never `\s`, which matches `\n` and would eat the blank line that
    // follows any line with a trailing space. `\r` is in the set because HTTP is a
    // CRLF protocol: `curl -i` prints a carriage return at the end of every header line
    // and one alone on the separator line, which a terminal doesn't show, a reader can't
    // type, and YAML would carry into the page as an invisible byte.
    .replace(/[ \t\r]+$/gm, "")
    .replace(/^\n+/, "")
    .replace(/\n+$/, "");
  return wgetBars(curlMeter(shellNoise(trimmed)));
}

/** stripArtifacts, plus masking of values nothing can pin. Used only to compare a page
 *  against a fresh run — never to write a page, or the timestamps and rates on it would
 *  read as literal <TIMESTAMP> and <RATE> placeholders instead of real captured output.
 *
 *  Order matters: `rates` matches wget's summary line after `timestamps` has replaced
 *  the stamp that opens it. */
export function normalise(text) {
  return rates(timestamps(stripArtifacts(text)));
}
