// The two modules the client code imports by URL rather than by path.
//
// Both are real files in `dist/` at runtime and neither exists where TypeScript would look for
// it: `/assets/search.js` is compiled out of `search.ts` beside this file by `src/assets.ts`, and
// `/pagefind/pagefind.js` is generated by the Pagefind indexer after the build. Declaring them
// gives each dynamic import a checked type instead of a cast, so a change to what either exports
// is a type error here rather than a dialog that silently does nothing in a browser.
//
// Wildcards rather than the exact specifiers: under `moduleResolution: "Bundler"` a rooted path is
// resolved as a file before ambient declarations are consulted, so `declare module
// "/assets/search.js"` is never reached. The wildcard form is.
//
// Named `ambient.d.ts` and not `search.d.ts`. A `.d.ts` sitting beside a `.ts` of the same name is
// read as that file's declarations, which took these two out of scope entirely and left both
// imports unresolvable.

/** The compiled search dialog, imported by `src/client/interaction.ts` on first open. */
declare module "/assets/*" {
  export function openSearch(): void;
}

/** Pagefind's own bundle, imported by `src/client/search.ts`.
 *
 *  The whole of what this site uses, declared here and nowhere else: `search.ts` names the type as
 *  `typeof import(...)` rather than restating it, because two hand-written descriptions of one
 *  third-party API is two things to keep in step and one of them will be updated alone.
 *
 *  Narrow on purpose. It describes what the dialog relies on, so a Pagefind release that renames
 *  one of these fails the typecheck here rather than emptying the dialog in a browser. Pagefind
 *  generates this bundle into `dist/` at index time and ships no types for it, which is why it is
 *  written by hand at all. */
declare module "/pagefind/*" {
  /** One result, as returned by `PagefindResult.data()`. */
  export interface PagefindResultData {
    url: string;
    /** Page text with the matched words wrapped in `<mark>`, already escaped by Pagefind. */
    excerpt: string;
    meta: { title: string };
  }
  export interface PagefindResult {
    data(): Promise<PagefindResultData>;
  }
  export interface PagefindSearch {
    results: PagefindResult[];
  }
  export function init(): Promise<void>;
  /** Resolves to null when a newer keystroke superseded this call. */
  export function debouncedSearch(query: string): Promise<PagefindSearch | null>;
}
